name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk
        pip install buildozer cython

    - name: Unzip project
      run: |
        unzip -o "myapp (2).zip" -d myapp
        cd myapp
        buildozer init
        sed -i 's/package.name = .*/package.name = InstaBot/' buildozer.spec
        sed -i 's/package.domain = .*/package.domain = org.test/' buildozer.spec
        sed -i 's/requirements = python3.*/requirements = python3,kivy/' buildozer.spec
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: myapp-apk
        path: myapp/bin/*.apk
